name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: |
          set -euxo pipefail
          docker build -t node-app:latest .
          docker images  

      - name: Push Docker image
        run: |
          set -euxo pipefail
          docker push ananth305/getting-started

      - name: Update values.yaml
        run: |
          cd nodeapp  # Adjust if necessary
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'devopshint'
          git config --global user.email 'devopshint@gmail.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
