name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Disable Docker Buildx
        run: |
          echo "DOCKER_CLI_EXPERIMENTAL=disabled" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/${IMAGE_NAME}:${GITHUB_SHA} .
          docker images  # Optional: List images for debugging purposes

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/${IMAGE_NAME}:${GITHUB_SHA}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${GITHUB_SHA}'|' values.yaml 
          git config --global user.name 'devopshint'
          git config --global user.email 'devopshint@gmail.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
