name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}

    # Option 1: Disable Buildx (if not desired)
    - name: Disable Docker Buildx (Optional)
      run: |
        echo "DOCKER_CLI_EXPERIMENTAL=disabled" >> $GITHUB_ENV  # Comment out this step if using Buildx

    # Option 2: Build with Buildx (if desired)
    - name: Build Docker image with Buildx (Optional)
      run: |
        docker buildx build --push --platform linux/amd64 -t $DOCKERHUB_USERNAME/${IMAGE_NAME}:${GITHUB_SHA} .  # Comment out this step if not using Buildx
      # ... (rest of the steps remain the same)

    # Standard Build (if not using Buildx options above)
    - name: Build Docker image (Standard)  # Only uncomment if not using Buildx options above
      run: |
        docker build -t $DOCKERHUB_USERNAME/${IMAGE_NAME}:${GITHUB_SHA} .

    - name: Push Docker image
      run: |
        docker push $DOCKERHUB_USERNAME/${IMAGE_NAME}:${GITHUB_SHA}

    - name: Update values.yaml
      run: |
        # Find the directory containing package.json
        app_dir=$(find . -name 'package.json' -type d)
        # Assuming values.yaml is in the same directory as package.json
        sed -i 's|APP_VERSION:.*|APP_VERSION: '${GITHUB_SHA}'|' "${app_dir}/values.yaml"
        git config --global user.name 'devopshint'
        git config --global user.email 'devopshint@gmail.com'
        git add "${app_dir}/values.yaml"
        git commit -m "Update values.yaml"
        git push
