name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Replace with Docker Hub access token or password
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          set -euxo pipefail
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          docker images  # Optional: List Docker images for debugging

      - name: Push Docker image
        run: |
          set -euxo pipefail
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Update values.yaml
        run: |
          cd helm  # Adjust if necessary
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'devopshint'
          git config --global user.email 'devopshint@gmail.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
